### ISSUE TITLE
No DB is created

### ISSUE THREAD

**Issue by dpffxhad** [WorldBrain/storex#12]
I've been trying to create extension with storex but it doesn't seem to create DB. I've followed docs and tried with exact same snippet but there is no DB created in extension(no errors logged to the console).

Extension repo : https://github.com/dpffxhad/extension-storex

**Comment by ShishKabab** [comment]
Did you try writing anything to the DB? Also, I see you've copied lots of things from Memex which are not really necessary. Maybe I should create some kind of boilerplate project for people to start from.

**Comment by dpffxhad** [comment]
I tried writing to DB and now I can see all tables in BG. Shouldn't it display DB with tables on  `storageManager.finishInitialization()` without having to write to DB? Is writing to DB mandatory with other backends too?

As DB isn't being displayed in BG I thought I was missing something and copied code from Memex.
>  Maybe I should create some kind of boilerplate project for people to start from.

That would be great.

**Comment by ShishKabab** [comment]
That probably depends on Dexie. It kinda makes sense to wait with creating the DB until the last possible moment, no?
