### ISSUE TITLE
License for storex

### ISSUE THREAD

**Issue by saro-saravanan** [WorldBrain/storex#13]
Storex solves a problem that I've often wondered about - thanks!

I see Memex is MIT licensed, but there's no license attached to Storex.  It would be great if you could address this issue please.

Thanks!

**Comment by ShishKabab** [comment]
Thanks for spotting this! It's been a while since I've included a license. Would be copying a license file and modifying the package.json be enough?

**Comment by saro-saravanan** [comment]
Yes, I believe so, thanks!

**Comment by ShishKabab** [comment]
Just added a License file to every repo on the `develop` branch, now only `package.json` is left  :)

**Comment by saro-saravanan** [comment]
Thank you!
